Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
import numpy as np
list1=[]
list2=[]
print("enter elements of 1st list\n")
i=0
while i<5:
    list1.append(int(input()))
    i=i+1
print("enter elements of 2nd list\n")
i=0
while (i<5):
    list2.append(int(input()))
    i=i+1
    
arr1=np.array(list1)
arr2=np.array(list2)

print("list1:",list1)
print("list2:",list2)
print("array 1:",arr1)
print("array 2:",arr2)

arr3=np.array(np.concatenate((arr1,arr2)))
print("concatenated array",arr3)

print("sorted array 1\n")
print(np.sort(arr1))

print("sorted array 2\n")
print(np.sort(arr2))

print("sorted concatenated array\n")
print(np.sort(arr3))

enter elements of 1st list

1
5
8
10
15
enter elements of 2nd list

2
6
9
20
25
list1: [1, 5, 8, 10, 15]
list2: [2, 6, 9, 20, 25]
array 1: [ 1  5  8 10 15]
array 2: [ 2  6  9 20 25]
concatenated array [ 1  5  8 10 15  2  6  9 20 25]
sorted array 1

[ 1  5  8 10 15]
sorted array 2

[ 2  6  9 20 25]
sorted concatenated array

[ 1  2  5  6  8  9 10 15 20 25]


Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print ("array dimension:",arr.ndim)
print ("array size:",arr.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array dimension: 2
array size: 12


Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [4]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1D ARRAY:",arr1)
rearr=np.reshape(arr1,(-1,2))
print("reshaped 2D:",rearr)

1D ARRAY: [1 2 3 4]
reshaped 2D: [[1 2]
 [3 4]]


In [5]:
import numpy as np
x = np.array([2,3,6,7,9])
y = x[:, np.newaxis]
print(y)

[[2]
 [3]
 [6]
 [7]
 [9]]


Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [6]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print("vertical stacking: \n",np.vstack((arr1,arr2)))
print("horizontal stacking: \n",np.hstack((arr1,arr2)))

vertical stacking: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stacking: 
 [[1 2 5 6]
 [3 4 7 8]]


Questions 6:
How to get unique items and counts of unique items?

In [7]:
a= np.array([1, 1, 2, 3, 4, 4, 5, 6])

np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [8]:
np.count_nonzero(np.unique(a))


6